databases:
  - name: notes_api_production
    databaseName: notes_api_production
    user: notes_api_production

services:
  - type: web
    name: notes_api_production
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes_api_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false